spring:
  application:
    name: javaServiceTreeFrameworkBakcendCore
  zipkin:
    enabled: true
    service.name: zipkin-service
    sender.type: web
    base-url: http://192.168.25.46:9411
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
  datasource:
    #Hibernate
    url: jdbc:mysql://192.168.25.46:3306/aRMS?characterEncoding=UTF-8&useLegacyDatetimeCode=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: mysqluser
    password: mysqluserpassword
    #mybatis
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.25.46:3306/aRMS?characterEncoding=UTF-8&useLegacyDatetimeCode=false
      username: mysqluser
      password: mysqluserpassword
  flyway:
    enabled: false
    url: jdbc:mysql://192.168.25.46:3306/aRMS?characterEncoding=UTF-8&useLegacyDatetimeCode=false
    user: mysqluser
    password: mysqluserpassword
    baseline-on-migrate: false           # flyway_schema_history 테이블을 자동으로 생성할지 여부
    locations: classpath:com/arms/db

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true
        use_sql_comments: false
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace

server:
  port: 31313
  servlet:
    session:
      timeout: 1800
  contextPath: /

# Database configuration props
database:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://192.168.25.46:3306/aRMS?characterEncoding=UTF-8&useLegacyDatetimeCode=false
  username: mysqluser
  password: mysqluserpassword