spring:
  application:
    name: javaServiceTreeFrameworkBakcendCore
  mvc:
    async:
      request-timeout: 7200
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: false
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  flyway:
    enabled: true
    url: jdbc:mysql://313.co.kr:3306/aRMS?characterEncoding=UTF-8&useLegacyDatetimeCode=false
    user: mysqluser
    password: mysqluserpassword
    baseline-on-migrate: true           # flyway_schema_history 테이블을 자동으로 생성할지 여부
    locations: classpath:com/arms/db
  main:
    allow-bean-definition-overriding: true

server:
  port: 31313
  servlet:
    session:
      timeout: 7200
  contextPath: /