spring:
  application:
    name: javaServiceTreeFrameworkBackendCore
  mvc:
    async:
      request-timeout: 7200
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: false
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  main:
    allow-bean-definition-overriding: true

logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml

springfox:
  documentation:
    swagger:
      v2:
        path: /backend-core-api
    swagger-ui:
      base-url: /backend-core-api

server:
  port: 31313
  address: 0.0.0.0
  servlet:
    session:
      timeout: 7200
  contextPath: /

requirement:
  delete:
    type: hard delete      # (두 가지 유형)
                            # soft delete - 이슈 제목 및 본문 삭제 수정 처리(default)
                            # hard delete - 삭제 API 호출 처리
