spring:
  profiles:
    active: dev
  datasource:
    #Hibernate
    url: jdbc:log4jdbc:mysql://www.313.co.kr:3306/aRMS?characterEncoding=UTF-8&useLegacyDatetimeCode=false
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #mybatis
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://www.313.co.kr:3306/aRMS?characterEncoding=UTF-8&useLegacyDatetimeCode=false
  flyway:
    enabled: true
    url: jdbc:mysql://www.313.co.kr:3306/aRMS?characterEncoding=UTF-8&useLegacyDatetimeCode=false
    baseline-on-migrate: true           # flyway_schema_history 테이블을 자동으로 생성할지 여부
    locations: classpath:com/arms/db

# Database configuration props
database:
  driver: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  url: jdbc:log4jdbc:mysql://www.313.co.kr:3306/aRMS?characterEncoding=UTF-8&useLegacyDatetimeCode=false

arms:
  detail:
    connect:
      url: 127.0.0.1:9999
  engine:
    url: http://127.0.0.1:33333
