spring:
  application:
    name: javaServiceTreeFrameworkBakcendCore
  zipkin:
    enabled: true
    service.name: zipkin-service
    sender.type: web
    base-url: http://192.168.25.46:9411
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
  datasource:
    url: jdbc:oracle:thin:@db.313.co.kr:1521:orcl
    driverClassName: oracle.jdbc.driver.OracleDriver
    username: OPERATION_DB
    password: OPERATION_DB_1234
  jpa:
    open-in-view: false
  main:
    allow-bean-definition-overriding: true

server:
  port: 31313
  servlet:
    session:
      timeout: 1800
  contextPath: /

# Database configuration props
database:
  driver: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@db.313.co.kr:1521:orcl
  username: OPERATION_DB
  password: OPERATION_DB_1234